version: '2'
services:

  database:
    build: .
    image: postgres:13.3
    restart: always
    container_name: database
    ports:
      - "54321:5432"

    environment:
      POSTGRES_PASSWORD: postgres
